export enum InstructionType {
  immReg = 0,
  regImm = 1,
  regImm8 = 2,
  regReg = 3,
  regMem = 4,
  memReg = 5,
  immMem = 6,
  regPtrReg = 7,
  immOffReg = 8,
  noArgs = 9,
  singleReg = 10,
  singleImm = 11,
}

export const InstructionTypeSize: Record<keyof typeof InstructionType, number> = {
  immReg: 4,
  regImm: 4,
  regImm8: 3,
  regReg: 3,
  regMem: 4,
  memReg: 4,
  immMem: 5,
  regPtrReg: 3,
  immOffReg: 5,
  noArgs: 1,
  singleReg: 2,
  singleImm: 3,
};

export interface InstructionMeta {
  instruction: string;
  opcode: number;
  type: InstructionType;
  size: number;
  mnemonic: string;
}

export const meta: InstructionMeta[] = [
  {
    instruction: "MOV_IMM_REG",
    opcode: 0x10,
    type: InstructionType.immReg,
    size: InstructionTypeSize.immReg,
    mnemonic: "mov",
  },
  {
    instruction: "MOV_REG_REG",
    opcode: 0x11,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "mov",
  },
  {
    instruction: "MOV_REG_MEM",
    opcode: 0x12,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "mov",
  },
  {
    instruction: "MOV_MEM_REG",
    opcode: 0x13,
    type: InstructionType.memReg,
    size: InstructionTypeSize.memReg,
    mnemonic: "mov",
  },
  {
    instruction: "MOV_IMM_MEM",
    opcode: 0x1B,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "mov",
  },
  {
    instruction: "MOV_REG_PTR_REG",
    opcode: 0x1C,
    type: InstructionType.regPtrReg,
    size: InstructionTypeSize.regPtrReg,
    mnemonic: "mov",
  },
  {
    instruction: "MOV_IMM_OFF_REG",
    opcode: 0x1D,
    type: InstructionType.immOffReg,
    size: InstructionTypeSize.immOffReg,
    mnemonic: "mov",
  },
  {
    instruction: "ADD_REG_REG",
    opcode: 0x14,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "add",
  },
  {
    instruction: "ADD_IMM_REG",
    opcode: 0x3F,
    type: InstructionType.immReg,
    size: InstructionTypeSize.immReg,
    mnemonic: "add",
  },
  {
    instruction: "SUB_IMM_REG",
    opcode: 0x16,
    type: InstructionType.immReg,
    size: InstructionTypeSize.immReg,
    mnemonic: "sub",
  },
  {
    instruction: "SUB_REG_IMM",
    opcode: 0x1E,
    type: InstructionType.regImm,
    size: InstructionTypeSize.regImm,
    mnemonic: "sub",
  },
  {
    instruction: "SUB_REG_REG",
    opcode: 0x1F,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "sub",
  },
  {
    instruction: "INC_REG",
    opcode: 0x35,
    type: InstructionType.singleReg,
    size: InstructionTypeSize.singleReg,
    mnemonic: "inc",
  },
  {
    instruction: "DEC_REG",
    opcode: 0x36,
    type: InstructionType.singleReg,
    size: InstructionTypeSize.singleReg,
    mnemonic: "dec",
  },
  {
    instruction: "MUL_IMM_REG",
    opcode: 0x20,
    type: InstructionType.immReg,
    size: InstructionTypeSize.immReg,
    mnemonic: "mul",
  },
  {
    instruction: "MUL_REG_REG",
    opcode: 0x21,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "mul",
  },
  {
    instruction: "LSF_REG_IMM",
    opcode: 0x26,
    type: InstructionType.regImm8,
    size: InstructionTypeSize.regImm8,
    mnemonic: "lsf",
  },
  {
    instruction: "LSF_REG_REG",
    opcode: 0x27,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "lsf",
  },
  {
    instruction: "RSF_REG_IMM",
    opcode: 0x2A,
    type: InstructionType.regImm8,
    size: InstructionTypeSize.regImm8,
    mnemonic: "rsf",
  },
  {
    instruction: "RSF_REG_REG",
    opcode: 0x2B,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "rsf",
  },
  {
    instruction: "AND_REG_IMM",
    opcode: 0x2E,
    type: InstructionType.regImm,
    size: InstructionTypeSize.regImm,
    mnemonic: "and",
  },
  {
    instruction: "AND_REG_REG",
    opcode: 0x2F,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "and",
  },
  {
    instruction: "OR_REG_IMM",
    opcode: 0x30,
    type: InstructionType.regImm,
    size: InstructionTypeSize.regImm,
    mnemonic: "or",
  },
  {
    instruction: "OR_REG_REG",
    opcode: 0x31,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "or",
  },
  {
    instruction: "XOR_REG_IMM",
    opcode: 0x32,
    type: InstructionType.regImm,
    size: InstructionTypeSize.regImm,
    mnemonic: "xor",
  },
  {
    instruction: "XOR_REG_REG",
    opcode: 0x33,
    type: InstructionType.regReg,
    size: InstructionTypeSize.regReg,
    mnemonic: "xor",
  },
  {
    instruction: "NOT",
    opcode: 0x34,
    type: InstructionType.singleReg,
    size: InstructionTypeSize.singleReg,
    mnemonic: "not",
  },
  {
    instruction: "JMP_NOT_EQ",
    opcode: 0x15,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "jne",
  },
  {
    instruction: "JNE_REG",
    opcode: 0x40,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "jne",
  },
  {
    instruction: "JEQ_REG",
    opcode: 0x3E,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "jeq",
  },
  {
    instruction: "JEQ_IMM",
    opcode: 0x41,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "jeq",
  },
  {
    instruction: "JLT_REG",
    opcode: 0x42,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "jlt",
  },
  {
    instruction: "JLT_IMM",
    opcode: 0x43,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "jlt",
  },
  {
    instruction: "JGT_REG",
    opcode: 0x44,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "jgt",
  },
  {
    instruction: "JGT_IMM",
    opcode: 0x45,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "jgt",
  },
  {
    instruction: "JLE_REG",
    opcode: 0x46,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "jle",
  },
  {
    instruction: "JLE_IMM",
    opcode: 0x47,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "jle",
  },
  {
    instruction: "JGE_REG",
    opcode: 0x48,
    type: InstructionType.regMem,
    size: InstructionTypeSize.regMem,
    mnemonic: "jge",
  },
  {
    instruction: "JGE_IMM",
    opcode: 0x49,
    type: InstructionType.immMem,
    size: InstructionTypeSize.immMem,
    mnemonic: "jge",
  },
  {
    instruction: "PSH_IMM",
    opcode: 0x17,
    type: InstructionType.singleImm,
    size: InstructionTypeSize.singleImm,
    mnemonic: "psh",
  },
  {
    instruction: "PSH_REG",
    opcode: 0x18,
    type: InstructionType.singleReg,
    size: InstructionTypeSize.singleReg,
    mnemonic: "psh",
  },
  {
    instruction: "POP",
    opcode: 0x1A,
    type: InstructionType.singleReg,
    size: InstructionTypeSize.singleReg,
    mnemonic: "pop",
  },
  {
    instruction: "CAL_IMM",
    opcode: 0x5E,
    type: InstructionType.singleImm,
    size: InstructionTypeSize.singleImm,
    mnemonic: "cal",
  },
  {
    instruction: "CAL_REG",
    opcode: 0x5F,
    type: InstructionType.singleReg,
    size: InstructionTypeSize.singleReg,
    mnemonic: "cal",
  },
  {
    instruction: "RET",
    opcode: 0x60,
    type: InstructionType.noArgs,
    size: InstructionTypeSize.noArgs,
    mnemonic: "ret",
  },
  {
    instruction: "HLT",
    opcode: 0xFF,
    type: InstructionType.noArgs,
    size: InstructionTypeSize.noArgs,
    mnemonic: "hlt",
  },
];
